edition = "2024"
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
max_width = 110
merge_derives = false
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_impl_items = true
trailing_comma = "Vertical"
use_try_shorthand = true
wrap_comments = true
